boot.o: boot.S multiboot.h x86_desc.h types.h
idt_linkage.o: idt_linkage.S
restore_ebp.o: restore_ebp.S
x86_desc.o: x86_desc.S x86_desc.h types.h
file_system.o: file_system.c file_system.h types.h system_calls.h lib.h
i8259.o: i8259.c i8259.h types.h lib.h idt_handler.h
idt_handler.o: idt_handler.c idt_handler.h types.h lib.h rtc.h \
  system_calls.h
idt_init.o: idt_init.c x86_desc.h types.h lib.h i8259.h idt_init.h \
  idt_handler.h idt_linkage.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h i8259.h debug.h \
  tests.h idt_init.h paging.h rtc.h file_system.h system_calls.h \
  schedule.h terminal.h
keyboard.o: keyboard.c keyboard.h types.h terminal.h idt_handler.h lib.h \
  i8259.h
lib.o: lib.c lib.h types.h terminal.h paging.h
paging.o: paging.c paging.h types.h system_calls.h terminal.h
rtc.o: rtc.c rtc.h types.h lib.h i8259.h terminal.h
schedule.o: schedule.c schedule.h types.h system_calls.h restore_ebp.h \
  i8259.h lib.h x86_desc.h paging.h terminal.h
system_calls.o: system_calls.c system_calls.h types.h terminal.h \
  keyboard.h rtc.h file_system.h x86_desc.h paging.h lib.h
terminal.o: terminal.c terminal.h types.h lib.h system_calls.h
tests.o: tests.c tests.h x86_desc.h types.h lib.h i8259.h idt_handler.h \
  idt_linkage.h idt_init.h paging.h rtc.h file_system.h keyboard.h \
  terminal.h
